### ISSUE TITLE
CREATE SCHEMA statement sometimes got error  'SQL0142N  The SQL statement is not supported'

### ISSUE THREAD

**Issue by maxatcn** [ibmdb/go_ibm_db#17] opened 2019-05-18 04:20 UTC
Dear team,

I am connecting to BigSQL with go_ibm_db. For now got an issue when executing sql 'CREATE SCHEMA XXX'
The code like,
```
tx, err := db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	//sql1
	sql := "CREATE SCHEMA \"" + schemaName + "\""

	_, err = tx.Exec(sql)

	if err != nil {
		log.Println(err.Error())
		return err
	}

	err = tx.Commit()
	if err != nil {
		return err
	}
```

As test result, I found,
1.  If sql statement set to 'CREATE SCHEMA XXX',   the first call got error ' [IBM][CLI Driver][DB2/LINUXX8664] SQL0142N  The SQL statement is not supported.\n"',  but a second same call immediately got successfully.
2.  If sql statement set to 'CREATE SCHEMA XXX;'(with a ;  at the end).   This way, the sql always got successfully.  Not any error returned, even there should be error returned.  
Such as, when creating a schema name to 'DD2', if the first run got successfully, the second run should get an error like, '[IBM][CLI Driver][DB2/LINUXX8664] SQL0601N  The name of the object to be created is identical to the existing name \"DD2\" of type \"SCHEMA\".    SQLSTATE=42710\n"'.   But this way,(with a ; at the end of the sql), the call always got successful response.

Can you please advise how to identify or fix the issue?  Thanks.

**Comment by akhilravuri1** [comment] 2019-05-18 05:07
Hi @maxatcn 
1) When I tried to execute the statement "CREATE SCHEMA XXXX" and it has worked for me for the first time itself. So can you please try it again and update me.

2) If we add ";" at the end of the statement, It always shows a successful message but it is not recreating the schema. When I checked the code it returns an error but it is not handled so we will update the code.

Thanks,
Akhil

**Comment by maxatcn** [comment] 2019-05-18 07:49
Thank you @akhilravuri1  for the quick response. 
I still got the error in Way 1, let me paste the output here,
```
[root@dv bin]# curl -H "Content-Type: application/json" -X POST http://localhost:2345/test/schema --data '{"schemaName":"DD4"}'
{"code":500,"message":"SQLExecute: {     } [IBM][CLI Driver][DB2/LINUXX8664] SQL0142N  The SQL statement is not supported.\n"}
[root@dv bin]# curl -H "Content-Type: application/json" -X POST http://localhost:2345/test/schema --data '{"schemaName":"DD4"}'
{"schemaName":"DD4"}
```
You see, the same call, the first one failed, but the second one got successfully.
The api logic is simple, just open a connection and call the CREATE SCHEMA XXX code I attached previously.
Thanks.

**Comment by akhilravuri1** [comment] 2019-05-18 08:06
Can you please paste the db2level output and goenv output.

Thanks,
Akhil

**Comment by maxatcn** [comment] 2019-05-18 08:53
OK, the db2level and  goenv info:
```
DB21085I  This instance or install (instance name, where applicable: "bigsql") 
uses "64" bits and DB2 code release "SQL11019" with level identifier 
"020A010F".
Informational tokens are "DB2 v11.1.9.0", "s190515", "BSQL190515AMD64", and Fix 
Pack "0".
```
and 
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tongxue/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/opt/gospace"
GOPROXY=""
GORACE=""
GOROOT="/opt/go"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-I/opt/gospace/src/github.com/ibmdb/clidriver/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/opt/gospace/src/github.com/ibmdb/clidriver/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build457605444=/tmp/go-build -gno-record-gcc-switches"
```
Thanks.

**Comment by akhilravuri1** [comment] 2019-05-20 14:20
Hi @maxatcn 
For the 2nd issue, I have pushed the code. You can pull the latest code and update me if there are any issues.

I am unable to reproduce the 1st issue. Can you please provide me the steps to reproduce the error.
It would be great if you provide me the docker image to reproduce the error.

Thanks,
Akhil

**Comment by akhilravuri1** [comment] 2019-05-20 14:21
Hi @maxatcn 
For the 2nd issue, I have pushed the code. You can pull the latest code and update me if there are any issues.

I am unable to reproduce the 1st issue. Can you please provide me the steps to reproduce the error.
It would be great if you provide me the docker image to reproduce the error.

Thanks,
Akhil

**Comment by maxatcn** [comment] 2019-05-20 23:50
Thank you @akhilravuri1 ,  I will test and update later for the way 2.

The BigSQL I tested has not got to GA officially.  You may not download and test at the moment.
But I would like help  if you want to add some diagnose code and print some information for further analysis.  Please let me know. 
Thank you.

**Comment by maxatcn** [comment] 2019-05-21 02:19
> Hi @maxatcn
> For the 2nd issue, I have pushed the code. You can pull the latest code and update me if there are any issues.
> 
> I am unable to reproduce the 1st issue. Can you please provide me the steps to reproduce the error.
> It would be great if you provide me the docker image to reproduce the error.
> 
> Thanks,
> Akhil

@akhilravuri1 , an update for the code fix for 2nd issue.  After the code fix, the behaviour change to the issue one.   Means, for the sql statement with end ';', the first call failed with SQL0142N, the second call got successfully.

```
[root@dv bin]# curl -i -H "Content-Type: application/json" -X POST http://localhost:3303/test/schemas/create --data '{"schemaName":"DSN14"}'
HTTP/1.1 500 Internal Server Error
Content-Type: application/json
Date: Tue, 21 May 2019 01:37:01 GMT
Content-Length: 127

{"code":500,"message":"SQLExecute: {     } [IBM][CLI Driver][DB2/LINUXX8664] SQL0142N  The SQL statement is not supported.\n"}
[root@dv bin]# curl -i -H "Content-Type: application/json" -X POST http://localhost:3303/test/schemas/create --data '{"schemaName":"DSN14"}'
HTTP/1.1 201 Created
Content-Type: application/json
Date: Tue, 21 May 2019 01:37:04 GMT
Content-Length: 23

{"schemaName":"DSN14"}
```

As I mentioned above,  the BigSQL in the test is not GAed officially, you might not download and test .  Please let me know if you want to add diagnose code for analysis.

Thank you.

**Comment by akhilravuri1** [comment] 2019-05-21 03:59
Hi @maxatcn 
1) Just create a small application with connection and execute the query.
2) Take the cli trace for unsuccessful and successful call and send me the files.
          How to take cli trace:-
                   db2trc on -f 1.trc
                   #Run the application
                   db2trc off
                    db2trc fmt -cli 1.trc 1.cli
If you send me the steps, how you installed db2 for bigsql and how you download the driver and configured it. I will do it in the same way.

Thanks,
Akhil

**Comment by akhilravuri1** [comment] 2019-05-21 06:15
Hi @maxatcn 

I made some changes to the code and pushed it. I don't know whether it works for you or not. Can you just pull the latest code and update me.

If it produces the error, can please follow the steps in the last comment and share me the trace files.

Thanks,
Akhil

**Comment by maxatcn** [comment] 2019-05-21 07:24
OK @akhilravuri1 ,  attached the trace file 
[1.cli.zip](https://github.com/ibmdb/go_ibm_db/files/3201173/1.cli.zip)

Also, clidriver download link: https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
After download and install,   set,
```
export DB2HOME=$HOME/clidriver
export CGO_CFLAGS=-I$DB2HOME/include
export CGO_LDFLAGS=-L$DB2HOME/lib
export LD_LIBRARY_PATH=$DB2HOME/lib
```
For the BigSQL I am testing, you may not find it.  Since it is in IBM Intranet.
As I tested in BigSQL v6.0GA, it is the same behaviours.  If you could find a BigSQL v5.x or v6.0 GA, it is the same.  (BTW, as I tested on Db2 LUW v10.5.7 and a Db2 LUW v11, there is no such issue).
Thanks.

**Comment by akhilravuri1** [comment] 2019-05-21 07:28
Have you pulled the latest code and tried it?
If yes can you paste me the output?

Thanks.

**Comment by maxatcn** [comment] 2019-05-21 09:21
Thank you @akhilravuri1 .  Unfortunately,  I got the same error message after pulling the latest code. 
Let me attach the trace file,


[db2_trace.zip](https://github.com/ibmdb/go_ibm_db/files/3201726/db2_trace.zip)

There are two trace file in the zip file,  t.cli is with sql statement 'CREATE SCHEMA "DS12"'，
while t_with_comma.cli is with statement with ';' at the end.
Can you please have a check and let me know if any operation neeed.  

Thank you.

**Comment by akhilravuri1** [comment] 2019-05-21 09:24
Hi
Just for the clarification. You are able to create the schema with the second call but not with the first call Right.

Thanks.

**Comment by maxatcn** [comment] 2019-05-21 09:43
Yes，  the second call successful, and the schema created. But the first call got failed with SQL0142N.

Plus:  this happens when connecting a BigSQL release via cli driver.  
But when connecting a Db2 LUW via cli driver, it works well(the sql successful in the first time.).

**Comment by akhilravuri1** [comment] 2019-05-21 09:48
This is very strange, working at the second call. can you list the schemas and see the name. If yes, try to create a table under the schema.
Thanks.

**Comment by maxatcn** [comment] 2019-05-21 10:01
I tried to create a table under the schema, for example 'DP12', it works.
![image](https://user-images.githubusercontent.com/19709103/58087111-7d89dd80-7bf2-11e9-90d1-10b5e1621aff.png)
Thanks.

**Comment by akhilravuri1** [comment] 2019-05-21 10:07
Ok..Thanks, @maxatcn 
Can you give the link where I can download the IBM bigsql server?
I have downloaded the IBM db2 Bigsql Sandbox but its working for me. Can you give the details on how to install IBM db2 Bigsql?

Thanks,
Akhil

**Comment by maxatcn** [comment] 2019-05-21 10:22
@akhilravuri1 ,  I tried but I did not find a public link to download official version.   But I found one for downloading a free edition,  https://www.ibm.com/products/db2-big-sql?mhq=bigsql&mhsrc=ibmsearch_p   can you please try it?
Thanks.

**Comment by akhilravuri1** [comment] 2019-05-21 10:25
Thanks, But I tried this. It requires 16GB dedicated RAM. My system is of 16 GB RAM when I tried to allocate total ram it crashes. So is there any other way.

**Comment by maxatcn** [comment] 2019-05-21 10:28
Thank you @akhilravuri1 ,  Let me ask around if any way we could go ahead. I may not update today, but I will try ASAP. 
Thank you.

**Comment by akhilravuri1** [comment] 2019-05-21 11:15
Hi @maxatcn 
We will run the code at cli level so that we be able to know whether the error is at go level or cli level.

create a file name.t and paste (change dsn string)
```
opt echo on
opt callerror on
SqlAllocEnv 1
SqlAllocConnect 1 1
SqlDriverConnect 1 1 "DATABASE=go;HOSTNAME=localhost;PORT=45050;UID=akhil;Pwd=*******;PROTOCOL=TCPIP" -3 255 sql_driver_noprompt
sqlallocstmt 1 1
sqlprepare 1 "CREATE SCHEMA akhil" -3
sqlexecute 1
SqlFreeStmt 1  Sql_close
SqlTransact 1 1 Sql_commit
Killenv 1
```

Open a cmd->type db2cli
It will open a new CLP prompt
cd to the path where the file is stored. (In CLP prompt)
Then run this command ( db2cli<name.t )

If the schema is created for the first time itself then the issue is at the godriver level.

Thanks.
Akhil

**Comment by maxatcn** [comment] 2019-05-21 12:07
OK, @akhilravuri1 , let me try it.
Just a question for the statement 'sqlprepare 1 "CREATE SCHEMA akhil" -3'.

Basically, if we want to create a schema name with lowercase, there will be quota to the schema name,otherwize Db2 will convert the schema name to uppercase automatically. 
So in my code, the statement,   'CREATE SCHEMA "XXX"', is always with quote.

In the statement 'sqlprepare 1 "CREATE SCHEMA akhil" -3'. How can I send a schema name with quote?  'sqlprepare 1 "CREATE SCHEMA "akhil""?   Seems this is invalid, with double quote inside another double quote. 

Thanks.

**Comment by maxatcn** [comment] 2019-05-21 12:23
Anyway, attach the test result at first,
the first run:
```
[root@dv bin]# ./db2cli<name.t
IBM DATABASE 2 Interactive CLI Sample Program
(C) COPYRIGHT International Business Machines Corp. 1993,1996
All Rights Reserved
Licensed Materials - Property of IBM
US Government Users Restricted Rights - Use, duplication or
disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
> > opt callerror on
> SqlAllocEnv 1
SQLAllocEnv: rc = 0 (SQL_SUCCESS) 
             CLI henv = 1, Test Driver henv = 1
> SqlAllocConnect 1 1
SQLAllocConnect: rc = 0 (SQL_SUCCESS) 
             CLI hdbc = 1, Test Driver hdbc = 1
> SqlDriverConnect 1 1 "DATABASE=bigsql;HOSTNAME=localhost;PORT=32051;UID=user999;Pwd=***********;PROTOCOL=TCPIP" -3 255 sql_driver_noprompt
SQLDriverConnect: rc = 0 (SQL_SUCCESS) 
SQLDriverConnect: ConnStrOut:
 		UID=user999;PWD=**********;DATABASE=bigsql;HOSTNAME=localhost;PORT=32051;PROTOCOL=TCPIP;
                  cbConnStrOut: 94
> sqlallocstmt 1 1
SQLAllocStmt: rc = 0 (SQL_SUCCESS) 
              CLI hstmt = 1, Test Driver hstmt = 1
> sqlprepare 1 "CREATE SCHEMA AN17;" -3
SQLPrepare: rc = 0 (SQL_SUCCESS) 
> sqlexecute 1
SQLExecute: rc = -1 (SQL_ERROR) 
SQLError: rc = 0 (SQL_SUCCESS) 
SQLError: SQLState     :      
          fNativeError : -142
          szErrorMsg   : [IBM][CLI Driver][DB2/6000] SQL0142N  The SQL statement is not supported.

          cbErrorMsg   : 74
SQLError: rc = 100 (SQL_NO_DATA_FOUND) 
> SqlFreeStmt 1  Sql_close
SQLFreeStmt: rc = 0 (SQL_SUCCESS) 
> SqlTransact 1 1 Sql_commit
SQLTransact: rc = 0 (SQL_SUCCESS) 
> Killenv 1
SQLDisconnect: rc = 0 (SQL_SUCCESS) 
SQLFreeConnect: rc = 0 (SQL_SUCCESS) 
SQLFreeEnv: rc = 0 (SQL_SUCCESS) 
> 
```

The second run:
```

[root@dv bin]# ./db2cli<name.t
IBM DATABASE 2 Interactive CLI Sample Program
(C) COPYRIGHT International Business Machines Corp. 1993,1996
All Rights Reserved
Licensed Materials - Property of IBM
US Government Users Restricted Rights - Use, duplication or
disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
> > opt callerror on
> SqlAllocEnv 1
SQLAllocEnv: rc = 0 (SQL_SUCCESS) 
             CLI henv = 1, Test Driver henv = 1
> SqlAllocConnect 1 1
SQLAllocConnect: rc = 0 (SQL_SUCCESS) 
             CLI hdbc = 1, Test Driver hdbc = 1
> SqlDriverConnect 1 1 "DATABASE=bigsql;HOSTNAME=localhost;PORT=32051;UID=user999;Pwd=************;PROTOCOL=TCPIP" -3 255 sql_driver_noprompt
SQLDriverConnect: rc = 0 (SQL_SUCCESS) 
SQLDriverConnect: ConnStrOut:
 		UID=user999;PWD=***********;DATABASE=bigsql;HOSTNAME=localhost;PORT=32051;PROTOCOL=TCPIP;
                  cbConnStrOut: 94
> sqlallocstmt 1 1
SQLAllocStmt: rc = 0 (SQL_SUCCESS) 
              CLI hstmt = 1, Test Driver hstmt = 1
> sqlprepare 1 "CREATE SCHEMA AN17;" -3
SQLPrepare: rc = 0 (SQL_SUCCESS) 
> sqlexecute 1
SQLExecute: rc = -1 (SQL_ERROR) 
SQLError: rc = 0 (SQL_SUCCESS) 
SQLError: SQLState     : 42710
          fNativeError : -601
          szErrorMsg   : [IBM][CLI Driver][DB2/6000] SQL0601N  The name of the object to be created is identical to the existing name "AN17" of type "SCHEMA".  SQLSTATE=42710

          cbErrorMsg   : 150
SQLError: rc = 100 (SQL_NO_DATA_FOUND) 
> SqlFreeStmt 1  Sql_close
SQLFreeStmt: rc = 0 (SQL_SUCCESS) 
> SqlTransact 1 1 Sql_commit
SQLTransact: rc = 0 (SQL_SUCCESS) 
> Killenv 1
SQLDisconnect: rc = 0 (SQL_SUCCESS) 
SQLFreeConnect: rc = 0 (SQL_SUCCESS) 
SQLFreeEnv: rc = 0 (SQL_SUCCESS) 
> 
```

Seems that the behaviours a little different with from api call,  the first call got SQL0142N, actually, the schema name created, so in the second call, it returned SQL0601N.

Thanks.

**Comment by akhilravuri1** [comment] 2019-05-21 12:51
sqlprepare 1 "CREATE SCHEMA ""akHil"""

**Comment by akhilravuri1** [comment] 2019-05-21 12:56
Thank you @maxatcn I think the same thing is happening with the go driver It is throwing the error but it is creating the schema.

Can you please do one more thing run the above thing again by a trace on  So that we can forward it to the clidriver development team and get clarified.

But this time You have to add to more steps in the trace:-
```
db2trc on -f 1.trc
Run the file
db2trc off

db2trc flw 1.trc 1.flw
db2trc fmt 1.trc 1.fmt
db2trc fmt -cli 1.trc 1.cli
db2trc fmt -c 1.trc 1.drda
```
and please add that .trc file also.

Thanks,
Akhil

**Comment by maxatcn** [comment] 2019-05-21 13:10
OK @akhilravuri1 , here is the trace files,
[db2_trace_with_comma.tar.gz](https://github.com/ibmdb/go_ibm_db/files/3202638/db2_trace_with_comma.tar.gz)
[db2_trace.tar.gz](https://github.com/ibmdb/go_ibm_db/files/3202639/db2_trace.tar.gz)
 Please  have a check and let me know if anything missed.

Thanks.

**Comment by akhilravuri1** [comment] 2019-05-21 13:18
Thank you @maxatcn 
Perfect all the files are included.

**Comment by akhilravuri1** [comment] 2019-05-22 04:57
Hi @maxatcn 
```
opt echo on
opt callerror on
SqlAllocEnv 1
SqlAllocConnect 1 1
SqlDriverConnect 1 1 "DATABASE=go;HOSTNAME=localhost;PORT=45050;UID=akhil;Pwd=******;PROTOCOL=TCPIP" -3 255 sql_driver_noprompt
sqlallocstmt 1 1
sqlexecdirect 1 "CREATE SCHEMA akhil2" -3
SqlFreeStmt 1  Sql_close
SqlTransact 1 1 Sql_commit
Killenv 1
```
can you do the trace again with this code without ";".
Thanks,
Akhil

**Comment by maxatcn** [comment] 2019-05-22 08:21
Sure, here is the trace file, 
[db2_trace_0522.tar.gz](https://github.com/ibmdb/go_ibm_db/files/3206382/db2_trace_0522.tar.gz)
Thank you @akhilravuri1.

**Comment by akhilravuri1** [comment] 2019-05-22 08:49
Is there any error while executing that file. Like the error which you got yesterday.SQL0142 Error

**Comment by akhilravuri1** [comment] 2019-05-22 08:59
Hi @maxatcn 


> Hi @maxatcn
> 
> ```
> opt echo on
> opt callerror on
> SqlAllocEnv 1
> SqlAllocConnect 1 1
> SqlDriverConnect 1 1 "DATABASE=go;HOSTNAME=localhost;PORT=45050;UID=akhil;Pwd=******;PROTOCOL=TCPIP" -3 255 sql_driver_noprompt
> sqlallocstmt 1 1
> sqlexecdirect 1 "CREATE SCHEMA akhil2" -3
> SqlFreeStmt 1  Sql_close
> SqlTransact 1 1 Sql_commit
> Killenv 1
> ```
> 
> can you do the trace again with this code without ";".
> Thanks,
> Akhil

please do the scan using this code. In this, we are calling Execute directly without prepare.
so paste the above code in name.t file and run it with the trace on.

paste me the output also.

Thanks,
Akhil

**Comment by maxatcn** [comment] 2019-05-22 09:22
> Hi @maxatcn
> 
> ```
> opt echo on
> opt callerror on
> SqlAllocEnv 1
> SqlAllocConnect 1 1
> SqlDriverConnect 1 1 "DATABASE=go;HOSTNAME=localhost;PORT=45050;UID=akhil;Pwd=******;PROTOCOL=TCPIP" -3 255 sql_driver_noprompt
> sqlallocstmt 1 1
> sqlexecdirect 1 "CREATE SCHEMA akhil2" -3
> SqlFreeStmt 1  Sql_close
> SqlTransact 1 1 Sql_commit
> Killenv 1
> ```
> 
> can you do the trace again with this code without ";".
> Thanks,
> Akhil

@akhilravuri1 ， the file attached db2_trace_0522.tar.gz was run  with this .   Yes,  the same error,  the first run returned SQL0142N and the second run returned SQL0601N.   Thank you.

**Comment by akhilravuri1** [comment] 2019-05-22 09:45
Ok @maxatcn 
May the files which you included in the below tar are wrong. Can you please check this once again.
Because the trace files contain prepare and execute call which will not be called if we use execdirect.
So can you check it once?

> Sure, here is the trace file,
> [db2_trace_0522.tar.gz](https://github.com/ibmdb/go_ibm_db/files/3206382/db2_trace_0522.tar.gz)
> Thank you @akhilravuri1.

Thanks,
Akhil

**Comment by maxatcn** [comment] 2019-05-22 10:05
Sorry, my fault, missed the sqlexecdirect line,
[db2_trace_052202.tar.gz](https://github.com/ibmdb/go_ibm_db/files/3206833/db2_trace_052202.tar.gz)

Here is the new db2 trace attached. With the direct exec, the first run got successfully.
Thanks.

**Comment by akhilravuri1** [comment] 2019-05-22 10:10
Ok @maxatcn 
 
I will let you know when we figure it out. As of now, I think the issue is with the server not with the driver. But anyway, let us confirm it.
 
Thanks,
Akhil

**Comment by akhilravuri1** [comment] 2019-05-22 10:31
Hi @maxatcn 

Firstly, thanks for doing all the traces.

So the error which you are getting at the first call is not because of go driver or cli driver It is from server side which we don't have the access.

Somehow create schema is not working with prepare and execute in BigSQL server. It supports ExecDirect only. Which is not yet implemented in Go-driver. We will let you know once it is developed in go driver.

Once again thanks for all the traces. 

Thanks,
Akhil

**Comment by maxatcn** [comment] 2019-05-22 10:55
Thank you @akhilravuri1  for the help . 

Do you want me to raise a request to BigSQL team, to check the prepare and execute issue?

**Comment by akhilravuri1** [comment] 2019-05-22 11:05
That is up to you @maxatcn 
 If you use Prepare and Execute in your application then it will be a problem for you but if you use Execdirect then Leave it.

Thanks,
Akhil

**Comment by akhilravuri1** [comment] 2019-05-23 05:01
Hi @maxatcn 
I've done some digging on this issue.

You know that there is a database/sql package which lies between your application and our driver.
When you call db.Exec(query) it goes through the database/sql package and comes to our go driver.
So this database/sql package is calling the prepare function and then calling the execute function. So we can't replace it with ExecDirect function. Because we can't change anything in database/sql package (GO's Standard lib package). So we are looking for an alternative it may take some time to figure it out.

Thanks,
Akhil

**Comment by maxatcn** [comment] 2019-05-23 09:34
Thank you for the update @akhilravuri1 .   Please let me know if you found an alternative.

**Comment by maxatcn** [comment] 2019-05-29 05:20
@akhilravuri1 , just an update,  I got one workaround from BigSQL team,  "begin execute immediate 'create schema' ; end"  
this works for CREATE SCHEMA for now.  I will keep this workaround until a better solution.
Thank you.

**Comment by maxatcn** [comment] 2019-05-29 05:20
BTW, I got one SP call issue and I will open in a separate issue.

**Comment by akhilravuri1** [comment] 2019-05-29 14:28
"begin execute immediate 'create schema' ; end"
Is this a Query @maxatcn 

Thanks,
Akhil

**Comment by maxatcn** [comment] 2019-05-30 00:12
This is not  a standard sql, but it works in the case and the schema created properly.
I could only use it as a workaround before a full enhancement added. @akhilravuri1 
Thanks.

**Comment by akhilravuri1** [comment] 2019-06-04 12:05
Closing the Issue as BigSQL does not support prepare and execute.
If there is an alternative we will let you know.

**Closed by akhilravuri1** 2019-06-04 12:05 UTC

**Comment by maxatcn** [comment] 2019-06-05 03:32
Thank you @akhilravuri1 .  Let me update if the prepare+exec support in BigSQL planned later.

**Comment by bimalkjha** [comment] 2024-10-14 13:28
@yabinma You need to check with BigSQL support team about any plan to support prepare+exec. It is out of scope for go driver. Thanks.
