### ISSUE TITLE
DecimalSize() could not recognize decimal correctly

### ISSUE THREAD

**Issue by maxatcn** [ibmdb/go_ibm_db#118] opened 2020-11-13 04:15 UTC
Hi Team, can you please help with an issue as below? Thanks.

Here is the definition from function DecimalSize()
```
// DecimalSize returns the scale and precision of a decimal type.
// If not applicable or if not supported ok is false.
func (ci *ColumnType) DecimalSize() (precision, scale int64, ok bool) {
	return ci.precision, ci.scale, ci.hasPrecisionScale
}
```

But in our testing, the `ok` returns `false` for Decimal type.
The database connected is  a BigSQL, and part of code as below,
```
// get columns
	columnNames := make([]*models.GetTableItems0, 0)
	for _, column := range columns {

		colName := column.Name()
		colTypeName := column.DatabaseTypeName()
		colLength, ok := column.Length()
		if !ok {
			colLength = 0
		}

		colPrecision, colScale, ok := column.DecimalSize()
		if !ok {
			colPrecision = 0
			colScale = 0
		}

                log.Println("column name: " + column.Name())
		log.Println("column Type: " + column.DatabaseTypeName())
		log.Printf("column length: %d", colLength)
		log.Printf("\ncolumn P C: v% %d %d", ok, colPrecision, colScale)

...

	}

```

![image](https://user-images.githubusercontent.com/19709103/99027810-1495e280-25a9-11eb-8812-7300006efc16.png)

You see that in the debug, columns  `PARTNO` and `QONHAND` are both Decimal, but `false` printed in the output.

**Comment by akhilravuri1** [comment] 2020-11-13 05:48
Hi @maxatcn 

I will try to reproduce the issue.

The scale of that column is Zero?

Tanks,
Akhil

**Comment by maxatcn** [comment] 2020-11-13 06:32
Hi @akhilravuri1 

Yes, in my testing, for the columns PARTNO decimal(9,0) and QONHAND decimal(9,0).

Thanks,
Max

**Comment by akhilravuri1** [comment] 2020-11-13 06:41
Okay...I am able to reproduce the issue with a scale of 0.

Please give me some time I will try to fix it.

Thanks,
Akhil

**Comment by akhilravuri1** [comment] 2020-11-13 14:19
Hi @maxatcn 

I have pushed the fix. Please install the go_ibm_db again.

Let me know if you are facing this issue again.

Thanks,
Akhil

**Comment by maxatcn** [comment] 2020-11-13 23:55
Thank you @akhilravuri1 .

In the testing, before getting the resultset, there is sql error returned,
```
sql: converting argument $1 type: unsupported type sql.Out, a struct
```

I am thinking, the error in code,
```
rows, err := db.Query(queryString, sql.Out{Dest: &diags})

	if rows == nil {
		log.Error(queryString)
		log.Println(diags)
		log.Error(err.Error())
		return nil, err
	}

	defer rows.Close()

	columns, err := rows.ColumnTypes()
```

The sql query is to call a SP and get resultset, `"call systool.PREVIEWTABLE('INVENTORY', 'ORACL10004:J15USER8', 'MAXROWS=0', ?);"`

The error is on code, `sql.Out{Dest: &diags}`.   
Any change on this?  We do have code to call sql.Out in other places as I know.

**Comment by akhilravuri1** [comment] 2020-11-17 04:58
Master has the latest fix.
There is no change in that sql.Out Code.
But error seems to be like struct is not supported. I assume you are passing the struct variable in the sql.Out but it is not supported, please pass any data type and check it.

Thanks,
Akhil

**Comment by maxatcn** [comment] 2020-11-17 07:37
@akhilravuri1 ,  the same code, it works in v0.2.0,   but it fails with master code, the error message, `sql: converting argument $1 type: unsupported type sql.Out, a struct`.     There should be difference between v0.2.0 and master. 
Can you please test sql.Out between v0.2.0 and master?   Thanks.

**Comment by akhilravuri1** [comment] 2020-11-17 07:39
Can you please provide a sample program that reproduces the issue?

Thanks,
Akhil

**Comment by akhilravuri1** [comment] 2020-11-17 07:42
Does your Db.Query call consists of (insert into tbname values(?), value) ?

thanks,
Akhil

**Comment by maxatcn** [comment] 2020-11-17 09:40
No, the sql used in the code is `"call systool.PREVIEWTABLE('INVENTORY', 'ORACL10004:J15USER8', 'MAXROWS=0', ?);"`.  3 input and one OUTPUT.  The only OUTPUT is VARCHAR type for diagnose information, named DIAGS.
You may not find this SP, because this is from a DV data source(based on BigSQL.)

@akhilravuri1 , let me try if this can be re-produced on a Db2 LUW.  If so, you can produce it on your own database. Update later.

**Comment by akhilravuri1** [comment] 2020-11-17 09:43
Hi @maxatcn 

Can you try calling db.Prepare(call systool.PREVIEWTABLE('INVENTORY', 'ORACL10004:J15USER8', 'MAXROWS=0', ?)) 
and st.Query(sql.Out{Dest: &diags});

Because in v0.3.0 we have introduced DirectExecute Api.

Thanks,
Akhil

**Comment by maxatcn** [comment] 2020-11-17 10:18
Hi @akhilravuri1 , yes, after adding Prepare(), it works and precision and scale returned the correct value.

```
var diags string
	st, err := db.Prepare(queryString)
	if err != nil {
		log.Error(err.Error())
		return nil, NewDvError(err, 500, err.Error())
	}

	rows, err := st.Query(sql.Out{Dest: &diags})
```

Is there anyway to compatible with v0.2.0 mode?  We have many code to use sql.Out{Dest: &diags}. Anyway we could avoid to add Prepare() every place?  Thanks.

**Comment by akhilravuri1** [comment] 2020-11-17 10:22
From v0.3.0 you have to call prepare and query.

Thanks,
Akhil

**Comment by maxatcn** [comment] 2020-11-17 10:30
OK @akhilravuri1 .   Is this applied to SP call only or any SELECT query?

**Comment by akhilravuri1** [comment] 2020-11-17 10:31
Any query.

Thanks,
Akhil

**Comment by maxatcn** [comment] 2020-11-17 10:35
Thank you for letting me know the details. @akhilravuri1 .

Regards,
Max

**Comment by akhilravuri1** [comment] 2020-11-17 10:37
no problem...I am closing this issue.

If you face any issues please feel free to raise an issue.

Thanks,
Akhil

**Closed by akhilravuri1** 2020-11-17 10:37 UTC

**Comment by maxatcn** [comment] 2020-11-18 01:32
Hi @akhilravuri1 ,

One more question please, we are planning to upgrade go_ibm_db in coming release.  Just want to confirm what's the plan for go_ibm_db's next release? Or which release will include the fix in the case?

You know, in the go.mod, it is specified to v0.2.0 for now,
`github.com/ibmdb/go_ibm_db v0.2.0`

We will change the tag/commit number in next release. `master` may not be the best label here.   Is there a fixed tab/release we could use it here?

Thanks,
Max
