### ISSUE TITLE
Error while creating database  SQLCreateDb

### ISSUE THREAD

**Issue by smilethensee** [ibmdb/go_ibm_db#173] opened 2022-08-08 07:42 UTC
Error while creating database  SQLCreateDb: {5U061} [IBM][CLI Driver][DB2/LINUXX8664] SQL1746W  The database, "Goo1", was successfully created.  However, database configuration was not automatically tuned for your system resources.  SQLSTATE=5U061

DB2 version is 10.5
OS：Linux

when I run the command of createDatabase, the error occur as below，what to do to solve this problem?

**Comment by vmathur12** [comment] 2022-08-09 04:18
Hi, @smilethensee 
I am trying to reproduce the problem. Thanks,

**Comment by vmathur12** [comment] 2022-08-12 04:37
Hi @smilethensee
The issue is not reproduceable in DB2 version 11.5.6.0 Please try in DB2 version 11.5.6.0

**Comment by vmathur12** [comment] 2022-08-16 03:07
@smilethensee I am closing this issue. Let me know if you are facing this issue DB2 version 11.5.6.0. Thanks

**Closed by vmathur12** 2022-08-16 03:07 UTC
