### ISSUE TITLE
Create duplicate view: Error object is nil

### ISSUE THREAD

**Issue by NateMoeller** [ibmdb/go_ibm_db#42] opened 2019-10-08 22:55 UTC
Hi,

Encountered an issue when creating a view which is a duplicate schema/name pair. The `CREATE VIEW` statement should fail as the view already exists within the database. Below is a sample program (Suppose there exists a table `USER999.WEB_PAGE`):

```
package main

import (
	"database/sql"
	"fmt"
	_ "github.com/ibmdb/go_ibm_db"
)

func main() {
	con := "HOSTNAME=<host>;PORT=<port>;DATABASE=<db>;UID=<username>;PWD=<password?"
	db, err := sql.Open("go_ibm_db", con)
	if err != nil {
		fmt.Println(err)

	}
	defer db.Close()
	
       createViewStmt := "CREATE VIEW \"USER999\".\"NATE_TEST\" as SELECT * from \"USER999\".\"WEB_PAGE\";"

       _, err := db.Exec(createViewStmt)
       if err == nil {
	    fmt.Println("err object is nil")
       } else {
	    fmt.Println("detected err", err)
       }

       _, err2 := db.Exec(createViewStmt)
       if err2 == nil {
	   fmt.Println("err2 object is nil")
       } else {
	   fmt.Println("detected err2", err2)
       }
}
```
The output is:
err object is nil
err2 object is nil

The first view is created correctly. However the 2nd execution of this statement should fail as this view already exists.

**Comment by akhilravuri1** [comment] 2019-10-09 07:04
Hi @NateMoeller 
If you give ';' at the end of the statement go might think that there is one more sql query to execute and does not return the error for the first query.

So please remove the ';' at the end of the statement and try to execute the query.

Thanks,
Akhil

**Comment by NateMoeller** [comment] 2019-10-09 17:27
@akhilravuri1 Without the `;`, the following output is produced:

```
detected err SQLExecute: {     } [IBM][CLI Driver][DB2/LINUXX8664] SQL0142N  The SQL statement is not supported.

detected err2 SQLExecute: {42S01} [IBM][CLI Driver][DB2/LINUXX8664] SQL0601N  The name of the object to be created is identical to the existing name "USER999.NATE_TEST" of type "VIEW".  SQLSTATE=42710
```

The first execution is reporting an error, however the statement is actually succeeding (the view is created). The second execution fails as expected.

Currently we cannot remove the semicolon as the first execution is reporting an error (incorrectly?).

**Comment by akhilravuri1** [comment] 2019-10-10 04:41
@NateMoeller 
with LUW server without ';' it is working fine.
which server are you using?

**Comment by akhilravuri1** [comment] 2019-10-10 07:51
@liuljun and @NateMoeller this error is thrown by the server our go driver cannot handle it.
please read this document https://www.ibm.com/support/knowledgecenter/en/SSCRJT_5.0.3/com.ibm.swg.im.bigsql.commsql.doc/doc/r0000935.html and check whether your view creation may fall in any of this case.

can you please create a view and try to get data from that view.

**Comment by NateMoeller** [comment] 2019-10-10 17:55
After the first execution of the above `CREATE VIEW` statement, I can successfully read the data. It still reports `SQL0142N  The SQL statement is not supported.`

#17 Seems to be a related issue.

**Comment by akhilravuri1** [comment] 2019-10-11 05:00
@NateMoeller please pull the code from iseries branch and run the program.

**Comment by NateMoeller** [comment] 2019-10-14 17:31
@akhilravuri1 Just tested with the iseries branch. The output of the test program is:

```
err object is nil
detected err2 SQLExecute: {42S01} [IBM][CLI Driver][DB2/LINUXX8664] SQL0601N  The name of the object to be created is identical to the existing name "USER999.NATE_TEST" of type "VIEW".  SQLSTATE=42710
```

This output is the same when using a semi colon or omitting the semi colon. This fix seems to work as I am no longer seeing the `SQL0142N The SQL statement is not supported.`

**Comment by xnxuen** [comment] 2019-10-15 08:36
I think maybe I encounter an issue which is similar with this one.
When I try removing a table with the following code
`
queryString := "drop nickname " + "\"" + "USER999" + "\"" + "." + "\"" + "SYBASE_OJOIN_PRODUCTS_EMPTY" + "\""

	_, err := db.Exec(queryString)

	if err != nil {
		fmt.Println(err.Error())
	}
`
There is an error occurred
`SQLExecute: {     } [IBM][CLI Driver][DB2/LINUXX8664] SQL0142N  The SQL statement is not supported.`
But the table `USER999.SYBASE_OJOIN_PRODUCTS_EMPTY` has been removed, since I re-run such code, there is another error occurred
`SQLExecute: {42704} [IBM][CLI Driver][DB2/LINUXX8664] SQL0204N  "USER999.SYBASE_OJOIN_PRODUCTS_EMPTY" is an undefined name.  SQLSTATE=42704`

**Comment by akhilravuri1** [comment] 2019-10-15 08:47
@xnxuen are you using BIGSQL?
please use iseries branch and run the program.

**Comment by xnxuen** [comment] 2019-10-16 08:12
OK, I will have a try when your code is ready. Thanks. @akhilravuri1

**Comment by xnxuen** [comment] 2019-10-21 01:56
@akhilravuri1 I just wonder if there is any progress, thanks.

**Comment by akhilravuri1** [comment] 2019-10-21 07:28
> please use iseries branch and run the program.



@xnxuen I have already updated the code to the iseries branch 7days ago.
 



> This output is the same when using a semi colon or omitting the semi colon. This fix seems to work as I am no longer seeing the `SQL0142N The SQL statement is not supported.`


This issue is fixed but it is opened because I did not merge the code to the master branch.

**Comment by akhilravuri1** [comment] 2019-10-21 07:53
the issue is fixed and code is merged to the master branch.

**Comment by NateMoeller** [comment] 2019-10-21 18:06
@akhilravuri1 I am not sure what changed, but I am now seeing `SQLExecute: {     } [IBM][CLI Driver][DB2/LINUXX8664] SQL0142N  The SQL statement is not supported.`. I am getting this error after every CREATE VIEW statement that is run. 

I am seeing this on both the master and iseries branch. This is odd as this seemed to work on the iseries branch last week. 

Can you take a look?

**Comment by akhilravuri1** [comment] 2019-10-22 05:58
Hi @NateMoeller 
please take the trace and share that with me.
```
db2trc on -f 1.trc
<Run the test to repro issue>
db2trc off

db2trc fmt -c 1.trc 1.drda

db2trc flw 1.trc 1.flw
db2trc fmt 1.trc 1.fmt
db2trc fmt -cli 1.trc 1.cli
```

Thanks,
Akhil

**Comment by NateMoeller** [comment] 2019-10-22 19:08
@akhilravuri1 
[1.txt](https://github.com/ibmdb/go_ibm_db/files/3757920/1.txt)

**Comment by akhilravuri1** [comment] 2019-10-23 07:31
@NateMoeller 
please zip and share the trc, flw, fmt and cli files.

**Comment by NateMoeller** [comment] 2019-10-23 21:13
The file is too large for Github, so I've uploaded the file to a server. I've emailed you instructions on how to access the zip file.

The go file I am running is very similar to the original sample code:

```
package main

import (
	"database/sql"
	"fmt"
	_ "github.com/ibmdb/go_ibm_db"
)

func main() {
	con := "HOSTNAME=<host>;PORT=<port>;DATABASE=<db>;UID=<username>;PWD=<password?"
	db, err := sql.Open("go_ibm_db", con)
	if err != nil {
		fmt.Println(err)

	}
	defer db.Close()
	
  createViewStmt := "CREATE VIEW \"USER999\".\"TEST_123\" as SELECT * from \"USER999\".\"ITEM\";"

  _, err := db.Exec(createViewStmt)
  if err == nil {
    fmt.Println("err object is nil")
  } else {
    fmt.Println("detected err", err)
  }
}
```

**Comment by akhilravuri1** [comment] 2019-10-24 05:35
> The file is too large for Github, so I've uploaded the file to a server. I've emailed you instructions on how to access the zip file.
> 
> The go file I am running is very similar to the original sample code:
> 
> ```
> package main
> 
> import (
> 	"database/sql"
> 	"fmt"
> 	_ "github.com/ibmdb/go_ibm_db"
> )
> 
> func main() {
> 	con := "HOSTNAME=<host>;PORT=<port>;DATABASE=<db>;UID=<username>;PWD=<password?"
> 	db, err := sql.Open("go_ibm_db", con)
> 	if err != nil {
> 		fmt.Println(err)
> 
> 	}
> 	defer db.Close()
> 	
>         createViewStmt := "CREATE VIEW \"USER999\".\"TEST_123\" as SELECT * from \"USER999\".\"ITEM\";"
> 
>         _, err := db.Exec(createViewStmt)
>         if err == nil {
>           fmt.Println("err object is nil")
>         } else {
>           fmt.Println("detected err", err)
>         }
> }
> ```
I have received the mail.
Thanks,
Akhil

**Comment by NateMoeller** [comment] 2019-10-25 18:02
@akhilravuri1 
[create_view_logs.zip](https://github.com/ibmdb/go_ibm_db/files/3773201/create_view_logs.zip)

**Comment by xnxuen** [comment] 2019-10-28 08:01
Hi @akhilravuri1 , may I know the progress of this issue? Thanks.

**Comment by akhilravuri1** [comment] 2019-10-28 13:17
Hi @xnxuen

I am on vacation till nov 3rd and will be back on nov 4th.

Thanks,
Akhil

**Comment by akhilravuri1** [comment] 2019-11-06 05:47
Hi @NateMoeller and @xnxuen 

I have investigated the log files which you have sent and from the logs, I can see the data sent to the BigSQL server and other servers (LUW, iSeries, ZOS) is same. But somehow the BigSQL server is returning the error message. If I receive the connection details of BigSQL I can double-check and 
confirm it.

**Comment by xnxuen** [comment] 2019-11-08 06:11
@akhilravuri1  Not sure whether you have access to the following playground
https://zen-cpd-zen.apps.nfscpd6-lb-1.fyre.ibm.com/
You may have a try.

**Comment by xnxuen** [comment] 2019-11-12 06:38
Hi @akhilravuri1 may I know the progress of this issue? Thanks.

**Comment by akhilravuri1** [comment] 2019-11-12 07:05
Hi @xnxuen 
sorry for the late reply.
I was not able to access the playground.

Thanks
Akhil

**Comment by ThuanQBui** [comment] 2019-12-02 16:47
@NateMoeller @xnxuen Can you provide the info for @akhilravuri1 to reproduce the problem?

**Comment by akhilravuri1** [comment] 2019-12-02 16:55
@ThuanQBui I will try to reproduce the issue when I get the details but I think this has to be solved from the server-side. As the server is throwing the error. 
If I get the details I will try to run the program with other drivers also or you can create a small node js program that creates a view or drop it.

Thanks,
AKhil

**Comment by liuljun** [comment] 2019-12-04 00:27
@akhilravuri1 I send the JDBC URL and credential to you via email. Please check.

**Comment by akhilravuri1** [comment] 2019-12-10 09:00
@liuljun @ThuanQBui 
I have seen the mail and was able to reproduce the issue. Using node js I was not able to reproduce the issue.
I am working on it.

Thanks,
Akhil

**Comment by akhilravuri1** [comment] 2019-12-11 05:35
Hi @NateMoeller @liuljun @xnxuen and @ThuanQBui 

This issue is with the server. I was able to reproduce the same with node js driver and cli driver also.

This error is thrown from the server. This issue occurs only when we create the view using prepare and query. If you use Exec (ExecuteDirect api in clidriver) then this error will not be reproduced. But our go driver internally calls prepare and query even if you call Exec() which is designed as per the Go's standard package (database/sql).

This error is thrown only for the first time when a view is created. I mean Suppose If you create the view name Goo1 then the server will return 'SQL0142N  The SQL statement is not supported.' But the view is created. Now drop the view and then create a view with the same name then the server is not returning any error.

```
package main

import (
	"database/sql"
	"fmt"
	_ "github.com/ibmdb/go_ibm_db"
)

func main() {
        con := "database=db;hostname=locaslhost;port=123;uid=uname;pwd=pass"
	db, err := sql.Open("go_ibm_db", con)
	if err != nil {
		fmt.Println(err)
	}
	defer db.Close()
	db.Exec("drop table rocket")
	db.Exec("CREATE table rocket(a int);")
	createViewStmt := "CREATE VIEW Goo1 as SELECT * from rocket;"
       _, err = db.Exec(createViewStmt)
       if err == nil {
	    fmt.Println("err object is nil")
       } else {
	    fmt.Println("detected err", err)
       }
      db.Exec("drop view Goo1")
       _, err2 := db.Exec(createViewStmt)
       if err2 == nil {
	   fmt.Println("err2 object is nil")
       } else {
	   fmt.Println("detected err2", err2)
       }
       db.Exec("drop view Goo1")
}
```
![image](https://user-images.githubusercontent.com/32290825/70593933-e7a4b700-1c04-11ea-8aa7-8b0b5094ef51.png)


From the above image, you can see that even we run the same application once again It is not throwing any error. But It throws only when we are creating the view for the first time in that server.

Thanks,
Akhil

**Comment by akhilravuri1** [comment] 2019-12-16 06:17
Hi @NateMoeller, @liuljun, @xnxuen, and @ThuanQBui 
Are you able to reproduce the issue?
Can I close the issue?
You can share the above go program which reproduces the issue with the BIG SQL server team.
If you need any CLI or node js program to reproduce the issue you can contact me.

Thanks,
Akhil

**Comment by liuljun** [comment] 2019-12-17 10:03
@akhilravuri1 Thanks for reproduce. We'll involve the BigSQL server team.

**Comment by akhilravuri1** [comment] 2020-01-28 06:06
Closing this issue as it is not in our scope.

**Closed by akhilravuri1** 2020-01-28 06:06 UTC
Labels: *out-of-scope, WaitingForInfo

**Comment by akhilravuri1** [comment] 2020-05-27 08:03
Hi @NateMoeller  @liuljun @xnxuen  and @ThuanQBui 

We have added DirectExecute api support. 
Last time you were facing this issue as BigSQL server is creating some problem if you call prepare and execute for creating a view or alter the table SQL's.

So now please give a try using direct execute api.
How to use direct execute API?

```
db.Query() will call direct execute api.
```
Note you cannot pass a parameter marker in direct execute SQL's.

Please let me know if you have any issues.

Thanks,
Akhil
