### ISSUE TITLE
Link Error `libdb2.so: undefined reference to sqloRemStgDelete`

### ISSUE THREAD

**Issue by cvigo** [ibmdb/go_ibm_db#189] opened 2022-10-27 22:00 UTC
I am having a similar issue that #177 but now with the recent version 11.5.8

```sh
# github.com/ibmdb/go_ibm_db/api
/usr/bin/ld: /usr/src/db2_clidriver/dsdriver/lib/libdb2.so: undefined reference to `sqloRemStgDelete'

```

Not sure what the "special build" that solved #177 is, but perhaps we need the same for 11.5.8

I opened a query to my IBM support team, will see if that helps

**Comment by vmathur12** [comment] 2022-11-24 02:36
@cvigo, Able to reproduce the issue. The issue is with clidriver 11.5.8.0. We are working on it.  Will update once the issue is resolved.

**Comment by dorudumitru-hh** [comment] 2023-01-20 09:18
Any news on this?

**Comment by vmathur12** [comment] 2023-01-20 13:22
@dorudumitru-hh The issue is fixed. Pull request: https://github.ibm.com/DB2/db2/pull/26260.

Official Special Build:

Platform: linuxamd64
Build ID: 270811
Fix Central URLs:
[odbc_cli](http://www.ibm.com/support/fixcentral/swg/quickorder?parent=ibm~Information%2BManagement&product=ibm/Information+Management/IBM+Data+Server+Client+Packages&release=All&platform=All&function=fixId&fixids=special_26260_270811_DSClients-linuxx64-odbc_cli-11.5.8.0-FP000%3A577209902003539072&includeSupersedes=0)
[dsdriver](http://www.ibm.com/support/fixcentral/swg/quickorder?parent=ibm~Information%2BManagement&product=ibm/Information+Management/IBM+Data+Server+Client+Packages&release=All&platform=All&function=fixId&fixids=special_26260_270811_DSClients-linuxx64-dsdriver-11.5.8.0-FP000%3A510049537921833024&includeSupersedes=0)
[jdbc_sqlj](http://www.ibm.com/support/fixcentral/swg/quickorder?parent=ibm~Information%2BManagement&product=ibm/Information+Management/IBM+Data+Server+Client+Packages&release=All&platform=All&function=fixId&fixids=special_26260_270811_DSClients--jdbc_sqlj-11.5.8.0-FP000%3A802097708109144448&includeSupersedes=0)
[universal_fixpack](http://www.ibm.com/support/fixcentral/swg/quickorder?parent=ibm~Information%2BManagement&product=ibm/Information+Management/DB2&release=All&platform=All&function=fixId&fixids=special_26260_270811_DB2-linuxx64-universal_fixpack-11.5.8.0-FP000%3A345173374837856704&includeSupersedes=0)
[rtcl](http://www.ibm.com/support/fixcentral/swg/quickorder?parent=ibm~Information%2BManagement&product=ibm/Information+Management/IBM+Data+Server+Client+Packages&release=All&platform=All&function=fixId&fixids=special_26260_270811_DSClients-linuxx64-rtcl-11.5.8.0-FP000%3A354572660162099200&includeSupersedes=0)
[server_dec](http://www.ibm.com/support/fixcentral/swg/quickorder?parent=ibm~Information%2BManagement&product=ibm/Information+Management/DB2&release=All&platform=All&function=fixId&fixids=special_26260_270811_DB2-linuxx64-server_dec-11.5.8.0-FP000%3A965876469258264320&includeSupersedes=0)
[client](http://www.ibm.com/support/fixcentral/swg/quickorder?parent=ibm~Information%2BManagement&product=ibm/Information+Management/IBM+Data+Server+Client+Packages&release=All&platform=All&function=fixId&fixids=special_26260_270811_DSClients-linuxx64-client-11.5.8.0-FP000%3A224466588579124704&includeSupersedes=0)

Thanks

**Comment by dorudumitru-hh** [comment] 2023-01-20 13:29
Thanks @vmathur12. Just a curiosity, we will need a special build with every new version of clidriver going forward?

**Comment by vmathur12** [comment] 2023-01-25 09:35
@dorudumitru-hh no need of special build for every new version of clidriver. Thanks

**Comment by vmathur12** [comment] 2023-01-26 02:50
@cvigo @dorudumitru-hh You can have fresh installation which will download latest clidriver from ibmsite.
Closing the issue. Let me know if you face this issue. Thanks

**Closed by vmathur12** 2023-01-26 02:50 UTC
