### ISSUE TITLE
Enhance setup.go code to allow for code refresh

### ISSUE THREAD

**Issue by baklarz** [ibmdb/go_ibm_db#51] opened 2019-12-23 17:45 UTC
The code within the setup.go uses a very simplistic technique to determine whether or not to install the cli driver for Db2:
```go
func main() {
...
	value, errDir := os.LookupEnv("DB2HOME")
	if errDir {
		if runtime.GOOS == "windows" {
			fmt.Println("clidriver is already present in this path ", value)
			fmt.Println("Please add this path to PATH environment variable")
			os.Exit(1)
		} else {
			fmt.Println("clidriver is already present in this path ", value)
			fmt.Println("Please set CGO_CFLAGS, CGO_LDFLAGS and LD_LIBRARY_PATH or DYLD_LIBRARY_PATH environment variables")
			os.Exit(1)
```
If I already have the environment variables set in my `.profile`, it will assume that everything is already installed and quits the installation. I was trying to update the driver to the latest version, and I can only do this if I remove all of the settings in `.profile` and basically restart the session. Any chance of having the code modified slightly so that it can prompt the user whether or not they really want to refresh the driver? The message is misleading since the entire directory had been deleted and recreated and the CLI libraries did not exist. This will also become an issue in the future when we update the CLI libraries and the process for doing this will be cumbersome if you rely on people removing their environment settings to refresh the code.

**Comment by akhilravuri1** [comment] 2020-01-28 06:04
Hi @baklarz 

We will look into this and try to add it in the next release.

Thanks,
Akhil

**Comment by akhilravuri1** [comment] 2020-05-12 05:42
Hi @baklarz 

The whole purpose of the DB2HOME variable is that not to download again...if you want to download please don't set this variable.

Thanks,
Akhil

**Comment by davidcmitchell** [comment] 2022-09-14 19:34
Can we reopen this? This is v annoying if you ever reinstall go

**Comment by vmathur12** [comment] 2022-10-26 10:00
@davidcmitchell 
go_ibm_db v0.4.2 is available now. The setup.go file is also modified could you please test it and let me know.
Thanks

**Comment by vmathur12** [comment] 2022-11-03 01:51
@davidcmitchell Updated the setup.go file, could you please test with the latest version and setup.go and let me know if you are still facing the problem. Thanks

**Comment by vmathur12** [comment] 2022-11-09 10:22
@davidcmitchell, the issue is fixed in pull request https://github.com/ibmdb/go_ibm_db/pull/188 .Thanks

**Closed** 2022-11-09 10:40 UTC
Labels: bug
