### ISSUE TITLE
fatal error: invalid pointer found on stack

### ISSUE THREAD

**Issue by eriklupander** [ibmdb/go_ibm_db#208] opened 2023-05-05 07:19 UTC
- os Version: scratch-based docker image
- cli-driver Version: 11.5, go_ibm_db version: 0.4.1 (we've also encountered this issue with 0.4.3)
- Db2 Server Version: 11.5
- go Version: 1.20.3
<details><summary><code>go env</code> Output: N/A, our runtime environment is a scratch container that only contains our binary + CLI-driver with dependencies, so cannot execute `go env` inside it.</summary><br><pre>
$ go env

</pre></details>

We are seeing very rare panics in our application when a transaction is commited:
```
runtime: bad pointer in frame github.com/ibmdb/go_ibm_db/api.SQLSetConnectAttr.func1 at 0xc00052ceb8: 0x1
```

Full stacktrace of the running goroutine (with some confidential information omitted)
```
	May 4th 2023, 01:21:14.524	goroutine 1 [running]:
github.com/ibmdb/go_ibm_db/api.SQLSetConnectAttr(0x91d3cb?, 0x0?, 0x933e56?, 0x45cf28?)	
	May 4th 2023, 01:21:14.524		/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.1/api/zapi_unix.go:119 +0x19 fp=0xc00052cef8 sp=0xc00052ced0 pc=0x91ea99	
	May 4th 2023, 01:21:14.524		/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.1/tx.go:19 +0x2f fp=0xc00052cf28 sp=0xc00052cef8 pc=0x92a28f	
	May 4th 2023, 01:21:14.524	github.com/ibmdb/go_ibm_db.(*Conn).endTx(0xc00010e000, 0x0?)	
	May 4th 2023, 01:21:14.524	database/sql.(*Tx).Commit.func1()	
	May 4th 2023, 01:21:14.524		/usr/local/go/src/database/sql/sql.go:3405 +0x8c fp=0xc00052cfd8 sp=0xc00052cf98 pc=0x847fcc	
	May 4th 2023, 01:21:14.524	<omitted> +0x19a fp=0xc00052d118 sp=0xc00052d038 pc=0x92c5fa	
	May 4th 2023, 01:21:14.524	<omitted>, _, {{0x0, 0x0}, {0x1, 0x1, 0x1, 0x5, 0x1f4, ...}, ...}, ...)	
	May 4th 2023, 01:21:14.524	<omitted>, _, {{0x0, 0x0}, {0x1, 0x1, 0x1, 0x5, 0x1f4, ...}, ...}, ...)	
	May 4th 2023, 01:21:14.524		<omitted> +0x1445 fp=0xc00052df80 sp=0xc00052d5f0 pc=0x932325	
	May 4th 2023, 01:21:14.522	runtime: bad pointer in frame github.com/ibmdb/go_ibm_db/api.SQLSetConnectAttr.func1 at 0xc00052ceb8: 0x1	
	May 4th 2023, 01:21:14.522	fatal error: invalid pointer found on stack	
```

This issue is very similar to an issue we encountered with another Go DB2 CLI driver wrapper (github.com/asifjalil/cli) a few years ago. In that case I reported https://github.com/asifjalil/cli/issues/17 which resulted in the following commit which solved our issue: https://github.com/asifjalil/cli/commit/2598d7f01fdb79080f4a7837561a9fbe019eda39

I can't say whether this driver wrapper suffers from the same issue (in particular, see https://github.com/asifjalil/cli/issues/17#issuecomment-650798417), but the issues seem so similar I think it warrants creating an issue in this project. 

This goroutine may also be of interest:
```
	May 4th 2023, 01:21:14.525	goroutine 34 [select]:	
	May 4th 2023, 01:21:14.525	runtime.selectgo(0xc000052790, 0xc000052770, 0x0?, 0x0, 0x0?, 0x1)	
	May 4th 2023, 01:21:14.525	database/sql.(*DB).connectionCleaner(0xc00027d1e0, 0x0?)	
	May 4th 2023, 01:21:14.525	runtime.gopark(0xffffffb0ffffffa?, 0xb?, 0x0?, 0x0?, 0x7?)	
	May 4th 2023, 01:21:14.525		/usr/local/go/src/runtime/netpoll.go:306 +0x89 fp=0xc00031d660 sp=0xc00031d640 pc=0x474589	
	May 4th 2023, 01:21:14.525	internal/poll.(*FD).Read(0xc000276c00, {0xc000164000, 0x1000, 0x1000})	
	May 4th 2023, 01:21:14.525		/usr/local/go/src/net/fd_posix.go:55 +0x29 fp=0xc00031d768 sp=0xc00031d720 pc=0x5c1e69	
	May 4th 2023, 01:21:14.524		
	May 4th 2023, 01:21:14.524		/usr/local/go/src/runtime/stack.go:632 +0x1d0 fp=0x7fff327c95f8 sp=0x7fff327c9590 pc=0x45d290	
	May 4th 2023, 01:21:14.524	runtime.adjustframe(0x7fff327c9988, 0x7fff327c9a68)	
	May 4th 2023, 01:21:14.524		/usr/local/go/src/runtime/traceback.go:332 +0xbed fp=0x7fff327c99e0 sp=0x7fff327c9688 pc=0x46a8cd	
	May 4th 2023, 01:21:14.524		/usr/local/go/src/runtime/stack.go:1064 +0x39b fp=0x7fff327c9d68 sp=0x7fff327c9bb8 pc=0x45e05b	
	May 4th 2023, 01:21:14.524	runtime.cgoCheckArg(0x988ee0?, 0x1?, 0x0?, 0x1?, {0xa74893?, 0x29?})	
	May 4th 2023, 01:21:14.524		/usr/local/go/src/runtime/cgocall.go:436 +0x165 fp=0xc00052ce88 sp=0xc00052ce40 pc=0x40fd05	
	May 4th 2023, 01:21:14.524	github.com/ibmdb/go_ibm_db/api.SQLSetConnectAttr.func1(0x45cf28?, 0xc0?, 0xc00045cf28?, 0xb30370?)	
	May 4th 2023, 01:21:14.524		/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.1/tx.go:54 +0x95 fp=0xc00052cf58 sp=0xc00052cf28 pc=0x92a495	
	May 4th 2023, 01:21:14.524		/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.1/tx.go:62 +0x25 fp=0xc00052cf78 sp=0xc00052cf58 pc=0x92a565	
	May 4th 2023, 01:21:14.524	database/sql.withLock({0xb30730, 0xc000110000}, 0xc00045d010)	
	May 4th 2023, 01:21:14.524	<omitted>({0xb32a40, 0xc0002885a0}, 0xc00011c6c0?, {0xbc0283, 0xa9f4, {0xc000492060, 0xb}, {{0xc000487140, 0x33}, 0x1}, ...}, ...)
	May 4th 2023, 01:21:14.524		<omitted> +0x3c8 fp=0xc00052d5f0 sp=0xc00052d480 pc=0x932a08
	May 4th 2023, 01:21:14.524	main.main()	
	May 4th 2023, 01:21:14.524	runtime stack:	
	May 4th 2023, 01:21:14.524	runtime.throw({0xa6c0f3?, 0x10c3b80?})	
	May 4th 2023, 01:21:14.524		/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7fff327c9590 sp=0x7fff327c9560 pc=0x44415d	
	May 4th 2023, 01:21:14.524	runtime.adjustpointers(0x7fff327c9988?, 0x0?, 0xd5426e?, {0xe98ee0?, 0x10c3b80?})	
	May 4th 2023, 01:21:14.524		/usr/local/go/src/runtime/stack.go:1216 +0x134 fp=0x7fff327c9bb8 sp=0x7fff327c9b98 pc=0x45ea94	
	May 4th 2023, 01:21:14.524	runtime.newstack()	
	May 4th 2023, 01:21:14.524	runtime.morestack()	
	May 4th 2023, 01:21:14.524		/usr/local/go/src/runtime/cgocall.go:446 +0x51f fp=0xc00052ce40 sp=0xc00052ce38 pc=0x41027f	
	May 4th 2023, 01:21:14.524	runtime.cgoCheckPointer({0x988ee0, 0x1}, {0x0, 0x0})	
	May 4th 2023, 01:21:14.524		/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.1/api/zapi_unix.go:119 +0x38 fp=0xc00052ced0 sp=0xc00052ce88 pc=0x91eb18	
	May 4th 2023, 01:21:14.524	github.com/ibmdb/go_ibm_db.(*Conn).setAutoCommitAttr(0xc00010e000, 0x0?)	
	May 4th 2023, 01:21:14.524	github.com/ibmdb/go_ibm_db.(*Tx).Commit(0x0?)	
	May 4th 2023, 01:21:14.524		/usr/local/go/src/database/sql/sql.go:2268 +0x2f fp=0xc00052cf98 sp=0xc00052cf78 pc=0x841f8f	
	May 4th 2023, 01:21:14.524	database/sql.(*Tx).Commit(0xc000706d00)	
	May 4th 2023, 01:21:14.524		/usr/local/go/src/database/sql/sql.go:2267 +0x10f fp=0xc00052d038 sp=0xc00052cfd8 pc=0x841e6f	
	May 4th 2023, 01:21:14.524		<omitted>
	May 4th 2023, 01:21:14.524		<omitted> +0xa12 fp=0xc00052d480 sp=0xc00052d118 pc=0x92c352
	May 4th 2023, 01:21:14.524	runtime.main()	
	May 4th 2023, 01:21:14.524		/usr/local/go/src/runtime/proc.go:250 +0x207 fp=0xc00052dfe0 sp=0xc00052df80 pc=0x446a47	
	May 4th 2023, 01:21:14.524		/usr/local/go/src/runtime/stack.go:674 +0xc9 fp=0x7fff327c9688 sp=0x7fff327c95f8 pc=0x45d3a9	
	May 4th 2023, 01:21:14.524	runtime.gentraceback(0x7f23b50f0631?, 0x1?, 0x7f23b6716880?, 0xc0000061a0, 0x0, 0x0, 0x7fffffff, 0xaa2058, 0x7f2373f031c8?, 0x0)	
	May 4th 2023, 01:21:14.524	runtime.copystack(0xc0000061a0, 0x0?)	
	May 4th 2023, 01:21:14.524		/usr/local/go/src/runtime/stack.go:934 +0x2f5 fp=0x7fff327c9b98 sp=0x7fff327c99e0 pc=0x45dbd5	
	May 4th 2023, 01:21:14.524	runtime.shrinkstack(0xc0000061a0)	
	May 4th 2023, 01:21:14.524		/usr/local/go/src/runtime/asm_amd64.s:574 +0x8b fp=0x7fff327c9d70 sp=0x7fff327c9d68 pc=0x477e8b	
	May 4th 2023, 01:21:14.524		
```

**Comment by eriklupander** [comment] 2023-05-08 07:00
Update / FYI:

We executed our application (which uses this module) with the `-gcflags=all=-d=checkptr` arguments, which reported two issues with unsafe pointers. One in `initDriver` in driver.go and one in `Conn.setAutoCommitAttr` in tx.go. 

By applying the changes from https://github.com/asifjalil/cli/commit/2598d7f01fdb79080f4a7837561a9fbe019eda39 into a local fork of this module, we got rid of the unsafe pointer warnings. Our application builds and runs fine with the modified go_ibm_db fork, but since the `fatal error: invalid pointer found on stack` error is very rare we'll need much more testing before we can say for sure it solved our problems.

**Comment by vmathur12** [comment] 2023-05-08 10:32
@eriklupander Could you please provide script/steps to reproduce this issue would be helpful. Thanks.

**Comment by eriklupander** [comment] 2023-05-08 10:57
Hi,

the actual error with `fatal error: invalid pointer found on stack` is very hard to reproduce, it happens so rarely I cannot really create a program that certainly would reproduce the problem. 

However, you can easily check the go_ibm_db module's codebase for bad pointer usage by entering the /testdata folder and run:

`go run -gcflags=all=-d=checkptr main.go`

This results in (truncated) running locally on my Mac:
```
fatal error: checkptr: pointer arithmetic computed bad pointer value

goroutine 1 [running, locked to thread]:
runtime.throw({0x10012a140?, 0x1000cfe40?})
	/usr/local/opt/go/libexec/src/runtime/panic.go:1047 +0x5d fp=0xc000066c38 sp=0xc000066c08 pc=0x10003491d
runtime.checkptrArithmetic(0x1?, {0x0?, 0x1001f0000?, 0x10034a9a8?})
	/usr/local/opt/go/libexec/src/runtime/checkptr.go:52 +0xbb fp=0xc000066c68 sp=0xc000066c38 pc=0x10000919b
github.com/ibmdb/go_ibm_db.initDriver()
	/Users/<username>/golang/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.3/driver.go:37 +0xb2 fp=0xc000066ce0 sp=0xc000066c68 pc=0x1000c6952
github.com/ibmdb/go_ibm_db.init.0()
	/Users/<username>/golang/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.3/driver.go:62 +0x3f fp=0xc000066d20 sp=0xc000066ce0 pc=0x1000c6b9f
runtime.doInit(0x1001e78a0)
```

**Comment by vmathur12** [comment] 2023-05-25 12:17
@eriklupander 
 We are seeing the checkptr issue because this is a new feature added in Go 1.14
 -d=checkptr as a compile-time option for adding instrumentation to check that Go code is following unsafe.Pointer safety rules dynamically. This can be disabled with -gcflags=all=-d=checkptr=0.
go run -gcflags=all=-d=checkptr=0 main.go

**Comment by eriklupander** [comment] 2023-05-29 09:39
Thanks for your answer.

The issue is that the code in driver.go and tx.go seems to be incorrect given that the checkptr check detects an issue. Turning off the checkptr check doesn't solve the root issue which is that we're getting those "invalid pointer found on stack" panics.

After applying the same fixes (in our local fork of this module) as in https://github.com/asifjalil/cli/commit/2598d7f01fdb79080f4a7837561a9fbe019eda39 we have not seen any more panics and the checkptr check runs without complaining.

**Comment by bimalkjha** [comment] 2023-06-18 08:13
Fix for this issue has been delivered using PR #215. Closing the issue now. Thanks.

**Closed by bimalkjha** 2023-06-18 08:13 UTC
