### ISSUE TITLE
The go_ibm_db driver cannot be registered sql: unknown driver "go_ibm_db" (forgotten import?)

### ISSUE THREAD

**Issue by andreamboni** [ibmdb/go_ibm_db#235] opened 2024-04-02 14:45 UTC
Hello, team. 

When I'm trying to connect to the database but I'm getting this error:

```
SQLGetDiagRec failed: ret=-2
The go_ibm_db driver cannot be registered
sql: unknown driver "go_ibm_db" (forgotten import?)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x20 pc=0x998ef5]

goroutine 1 [running]:
database/sql.(*DB).Close(0x0)
        C:/Users/andre/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/database/sql/sql.go:877 +0x35
main.main()
        C:/Users/andre/Documents/ETL/ETL-demo/etl-db2-connect/hello-db2.go:16 +0x75
exit status 2
```

I'm using Windows 10 VM with go version 1.21.8. 

I'm using the clidriver that were downloaded when I ran the setup.go file and I already configured the environment variables as follows: 

clidrvpath=C:\Users\andre\go\pkg\mod\github.com\ibmdb\clidriver
IBM_DB_HOME=%clidrvpath%
PATH=%PATH%;%IBM_DB_HOME%\bin

I'm trying to run the sample code in the README. 

```
package main

import (
	"database/sql"
	"fmt"

	_ "github.com/ibmdb/go_ibm_db"
)

func main() {
	con := "HOSTNAME=<HOSTNAME>;DATABASE=<DATABASE>;PORT=<PORT>;UID=<UID>;PWD=<PWD>"
	db, err := sql.Open("go_ibm_db", con)
	if err != nil {
		fmt.Println(err)
	}
	db.Close()

}
```
I've been searching for solutions but I can find anything that solves this problem. 

Thanks!

**Comment by vmathur12** [comment] 2024-04-03 01:47
Hi @andreamboni ,
Please run the following command in the same directory and share the output
>go mod init <>
>go mod tidy
>go  env

echo %IBM_DB_HOME%
echo %PATH%
Thanks

**Comment by andreamboni** [comment] 2024-04-03 02:19
Hello, @vmathur12,

I already created the go.mod file: 

```
module etl/db2connect

go 1.21.8

require github.com/ibmdb/go_ibm_db v0.4.5
```

and already ran the `go mod tidy`, but I ran again as per your request. I didn't get any output from it. 

Here is the output for the `go env` command: 

```
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\andre\AppData\Local\go-build
set GOENV=C:\Users\andre\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\andre\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\andre\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Users\andre\go\pkg\mod\golang.org\toolchain@v0.0.1-go1.21.8.windows-amd64
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Users\andre\go\pkg\mod\golang.org\toolchain@v0.0.1-go1.21.8.windows-amd64\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.8
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=C:\Users\andre\Documents\ETL\ETL-demo\etl-db2-connect\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\andre\AppData\Local\Temp\2\go-build2134941010=/tmp/go-build -gno-record-gcc-switches
```

The output for **IBM_DB_HOME**: C:\Users\andre\go\pkg\mod\github.com\ibmdb\clidriver
And the out put for the **PATH**: C:\Program Files\Zulu\zulu-17\bin\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;M:\IBM\info\Server\DSComponents\bin;C:\Program Files (x86)\MKS Toolkit\mksnt;C:\PROGRA~2\MKSTOO~1\bin64;C:\PROGRA~2\MKSTOO~1\bin;C:\PROGRA~2\MKSTOO~1\bin\X11;C:\PROGRA~2\MKSTOO~1\mksnt;M:\IBM\info/jdk32\jre\bin;M:\IBM\info/jdk32\jre\bin\j9vm;M:\IBM\info\ASBNode\lib\cpp;M:\IBM\info\ASBNode\apps\proxy\cpp\win32-all-x86;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\ibm\gsk8\lib64;C:\Program Files (x86)\ibm\gsk8\lib;C:\PROGRA~1\IBM\SQLLIB\BIN;C:\PROGRA~1\IBM\SQLLIB\FUNCTION;C:\PROGRA~1\IBM\SQLLIB\SAMPLES\REPL;M:\IBM\info\Server\PXEngine\bin;C:\Windows/SysWOW64;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Microsoft SQL Server Migration Assistant for DB2\bin\;C:\Program Files\Microsoft OLE DB Provider for DB2\System\;C:\Program Files\Git\cmd;C:\Program Files\Go\bin;**C:\Users\andre\go\pkg\mod\github.com\ibmdb\clidriver\bin**;C:\Program Files\Maven\apache-maven-3.9.6\bin;C:\Users\andre\AppData\Local\Microsoft\WindowsApps;C:\Users\andre\go\bin

Let me know if you need more information.

Thanks!

**Comment by vmathur12** [comment] 2024-04-04 11:02
@andreamboni 
When the driver failed to load the db2cli64.dll this problem will occurs
Please check C:\Users\andre\go\pkg\mod\github.com\ibmdb\clidriver\bin db2cli64.dll  is present.
Share the output of  ">ls -l C:\Users\andre\go\pkg\mod\github.com\ibmdb\clidriver\bin"
Thanks.

**Comment by andreamboni** [comment] 2024-04-04 11:50
Hello, @vmathur12.

Here is the output. The db2cli64.dll is in the clidriver\bin folder: 

```
PS C:\Users\andre\Documents\ETL> ls C:\Users\andre\go\pkg\mod\github.com\ibmdb\clidriver\bin


    Directory: C:\Users\andre\go\pkg\mod\github.com\ibmdb\clidriver\bin


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         4/1/2024   5:20 PM                amd64.VC12.CRT
d-----         4/1/2024   5:20 PM                icc64
-a----         4/1/2024   5:20 PM       41619456 db2app64.dll
-a----         4/1/2024   5:20 PM        1053184 db2cli.exe
-a----         4/1/2024   5:20 PM          22528 db2cli64.dll
-a----         4/1/2024   5:20 PM          24576 db2clixml4c64.dll
-a----         4/1/2024   5:20 PM         713728 db2ldap64.dll
-a----         4/1/2024   5:20 PM         224768 db2ldapm64.dll
-a----         4/1/2024   5:20 PM          53760 db2level.exe
-a----         4/1/2024   5:20 PM        4124160 db2osse64.dll
-a----         4/1/2024   5:20 PM         158208 db2support.exe
-a----         4/1/2024   5:20 PM        1554432 db2trc.exe
-a----         4/1/2024   5:20 PM         105472 db2trcapi64.dll
-a----         4/1/2024   5:20 PM          24576 db2trcd64.exe
-a----         4/1/2024   5:20 PM        4140032 DB2xml4c_cli64_5_8.dll
-a----         4/1/2024   5:20 PM            388 DB2xml4c_cli64_5_8.dll.2.manifest
-a----         4/1/2024   5:20 PM            521 IBM.DB2.APP64.manifest
-a----         4/1/2024   5:20 PM            396 IBM.DB2.CLI64.manifest
-a----         4/1/2024   5:20 PM            357 IBM.DB2.CLIXML4C64.manifest
-a----         4/1/2024   5:20 PM            427 IBM.DB2.LDAP64.manifest
-a----         4/1/2024   5:20 PM            428 IBM.DB2.LDAPM64.manifest
-a----         4/1/2024   5:20 PM            449 IBM.DB2.SEC64.manifest
-a----         4/1/2024   5:20 PM          45568 IBMIAMauth64.dll
-a----         4/1/2024   5:20 PM          62464 IBMkrb564.dll
-a----         4/1/2024   5:20 PM          64000 IBMkrb5TwoPart64.dll
-a----         4/1/2024   5:20 PM         587264 IBMLDAPauthclient64.dll
-a----         4/1/2024   5:20 PM          45056 IBMOSauthclient64.dll
-a----         4/1/2024   5:20 PM          45568 IBMOSauthclientTwoPart64.dll
```

Let me know in case you need more information. 

Thanks.

**Comment by vmathur12** [comment] 2024-05-13 03:21
@andreamboni, sorry for the delay in response. The issue is not reproducing in my setup could you please take the trace and share the trace files.
trace commands
db2trc on -f trc1.dmp 
<Run the test to repro issue>
db2trc off
db2trc fmt -c trc1.dmp trc1.drda
db2trc flw trc1.dmp trc1.flw
db2trc fmt trc1.dmp trc1.fmt
db2trc fmt -cli trc1.dmp trc1.cli
Thanks.

**Comment by vmathur12** [comment] 2024-05-27 03:59
@andreamboni Could you please share the trace files. Thanks

**Comment by vmathur12** [comment] 2024-05-29 05:08
@andreamboni Closing the issue. Let me know if you are facing this issue again. Thanks

**Closed by vmathur12** 2024-05-29 05:08 UTC
