### ISSUE TITLE
Unsupported Column Type Error-360

### ISSUE THREAD

**Issue by sasha27** [ibmdb/go_ibm_db#147] opened 2021-11-03 20:30 UTC
- os Version: AIX 7.2
- cli-driver Version: CLI v11.5.5.0
- Db2 Server Version: 11.5.5
- go Version: go1.14.2 aix/ppc64

I have been running into the following error while trying to run a query. I can post the query later if need be but this is what I see.
The error:
```bash
due to error unsupported column type -360" 
```
My peer doesn't run into this issue on their system but I happen to. After going through the code base here I see that this is being generated from https://github.com/ibmdb/go_ibm_db/blob/44b92183cf2e94a6de9f8793efc10cb46a519a98/column.go#L114 file. 

Can someone point me out to what's causing this issue and what is so specifically causing it?

**Comment by bimalkjha** [comment] 2021-11-09 19:54
@sasha27 If we grep for -360 under clidriver/include directory, we can see in sqlcli.h file, it is defined as below:
```sqlcli.h:#define  SQL_DECFLOAT           (-360)
```
It means your table has a DECFLOAT column which is causing the issue.
I can see, SQL_DECFLOAT is handled at line no 97 of [same file](https://github.com/ibmdb/go_ibm_db/blob/44b92183cf2e94a6de9f8793efc10cb46a519a98/column.go#L97). So, it should work. Probably, you are using an older version of go ibm_db driver, so upgrade to the latest version. Thansk.

**Comment by bimalkjha** [comment] 2021-11-09 20:02
@sasha27 It looks duplicate of closed issue #54.

**Comment by sasha27** [comment] 2021-11-09 21:35
@bimalkjha Is the cli-driver Version: CLI v11.5.5.0 i have mentioned not up to date? I have used the latest go IBM driver as well, i.e. the latest code base. Could you tell me how to check the version of the code or something so we can make sure I am on the latest. As of now I do a go mod and it gets the latest.

**Comment by vmathur22** [comment] 2021-11-10 04:37
@sasha27 Use "go version" command to check the version of the code.

**Comment by bimalkjha** [comment] 2021-11-10 13:57
@sasha27 My question was about go ibm_db driver code not the clidriver code. If you can access the source code in your system for ibm_db, check file column.go has the same code for DECFLOAT that I mentioned in first comment to make sure your code has the fix. If you are using latest go_ibm_db  code from github, then share some test program to reproduce the issue. Thanks.

**Comment by bimalkjha** [comment] 2021-11-23 04:50
@sasha27 Are you still facing this issue? Thanks.

**Closed** 2022-01-06 18:42 UTC
