### ISSUE TITLE
String OUT Parameters losing last character

### ISSUE THREAD

**Issue by Speshl** [ibmdb/go_ibm_db#100] opened 2020-07-16 14:08 UTC
- os Version: Windows 10
- cli-driver Version: Unsure, -help didn't list a version command
- Db2 Server Version: 12
- go Version: 1.13

Seems to only be happening for string parameters. Int are returning properly for sure.  Please let me know if you need anything an addition to the information listed below.

Stored procedure included should return in params back as outparams so you can see that character go missing.

[Example_Code.zip](https://github.com/ibmdb/go_ibm_db/files/4931893/Example_Code.zip)

Expected Output displaying bug:
sqlString = CALL MCS1D2.MCSSP_TEST_CALL_FROM_GO_3(?, ?, ?, ? ,? ,?, ?, ?)
doing stuff without prepare
Stored Procedure Input Parameters:
        in1 = 01/23/4567 in2 = AB in3 = 123456789012345678901234, in4 = 123
resultA = {Locker:0xc0000a0000 resi:0xc00000c240}
Stored Procedure Output Parameters:
        out1 = #01/23/456# out2 = #A# out3 = #12345678901234567890123#, out4 = #123#
doing stuff with prepare
Stored Procedure Input Parameters:
        in1 = 01/23/4567 in2 = AB in3 = 123456789012345678901234, in4 = 123
resultB = {Locker:0xc0000a0000 resi:0xc00000c300}
Stored Procedure Output Parameters:
        out1 = #01/23/456# out2 = #A# out3 = #12345678901234567890123#, out4 = #123#

**Comment by akhilravuri1** [comment] 2020-07-20 05:04
Hi @Speshl 

I will try to reproduce the issue.

Thanks,
Akhil

**Comment by Speshl** [comment] 2020-07-20 05:10
The pending pull request related to this from someone on my team.  That
seemed to resolve the issue but we haven't tested in depth.

Thanks,
Chaz

**Comment by akhilravuri1** [comment] 2020-07-20 05:17
> but we haven't tested in depth.

Thanks for the pull req we will run the test cases before merging it.

-Akhil

**Comment by akhilravuri1** [comment] 2020-07-24 07:51
Hi @Speshl 

I am unable to reproduce the issue.

Please run the below code and paste the output:-
```
package main

import (
	"fmt"
	_ "github.com/ibmdb/go_ibm_db"
	"database/sql"
)

func main(){
	con := "PROTOCOL=tcpip;HOSTNAME=localhost;PORT=60000;DATABASE=db;UID=uid;PWD=pass";
	db, _ := sql.Open("go_ibm_db", con);

	// IN ,OUT and INOUT for a stored procedure
	in1 := 10;
	inout1 := "Golang"
	var out1 string;
	st, err := db.Prepare("create or replace procedure sp1(in var1 integer, out var2 varchar(7), inout var3 varchar(7)) LANGUAGE SQL BEGIN   SET var2 = var3;  set var3 = 'SUCCESS'; END");
	if err != nil {
		fmt.Println("error while preparing sp1");
	}
	_, err = st.Query();
	if err.Error() != "Stmt did not create a result set" {
		fmt.Println(err);
		fmt.Println("error while creating sp1");
	}
	st, err = db.Prepare("CALL sp1(?,?,?)");
	if err != nil {
		fmt.Println("error while preparing sp1 CALL");
	}
	_, err = st.Query(in1, sql.Out{Dest: &out1}, sql.Out{Dest: &inout1, In: true});
	if err.Error() != "Stmt did not create a result set" {
		fmt.Println(err);
		fmt.Println("error while retriving data for sp1 with prepare");
	} 

	if inout1 != "SUCCESS" || out1 != "Golang" {
		fmt.Println("Data not Retrived Correctly in prepare");
		fmt.Println(out1);
		fmt.Println(inout1);
	} else {
		fmt.Println(out1);
		fmt.Println(inout1);
	}
	inout1 = "Golang"
	_, err = db.Exec("CALL sp1(?,?,?)", in1, sql.Out{Dest: &out1}, sql.Out{Dest: &inout1, In: true});
	if err != nil {
		fmt.Println("error while retriving data for sp1 with execute");
	}

	if inout1 != "SUCCESS" || out1 != "Golang" {
		fmt.Println("Data not Retrived Correctly in execute");
		fmt.Println(out1);
		fmt.Println(inout1);
	} else {
		fmt.Println(out1);
		fmt.Println(inout1);
	}	
}
```

Thanks,
Akhil

**Comment by Speshl** [comment] 2020-07-24 15:54
I ran your test case and it looks good, but your test uses a 6 character string "Golang" in a 7 character field.  Below is your same code with a 7 character string "1234567" in a 7 character field and it drops the last character.

Also if you do the test with 1 character string "F" in a 1 chracter field, and you will just get an empty string back.

```
package main

import (
	"database/sql"
	"fmt"

	_ "github.com/ibmdb/go_ibm_db"
)

//Preparing Statement
//error while creating sp1
//Data not Retrived Correctly in prepare
//123456
//SUCCESS
//error while retriving data for sp1 with execute
//Data not Retrived Correctly in execute
//123456
//1234567

func main() {
	con := "PROTOCOL=tcpip;HOSTNAME=localhost;PORT=60000;DATABASE=db;UID=uid;PWD=pass"
	db, _ := sql.Open("go_ibm_db", con)

	// IN ,OUT and INOUT for a stored procedure
	in1 := 10
	inout1 := "1234567"
	var out1 string
	fmt.Println("Preparing Statement")
	st, err := db.Prepare("create or replace procedure sp1(in var1 integer, out var2 varchar(7), inout var3 varchar(7)) LANGUAGE SQL BEGIN   SET var2 = var3;  set var3 = 'SUCCESS'; END")
	if err != nil {
		fmt.Println("error while preparing sp1")
	}
	_, err = st.Query()
	if err.Error() != "Stmt did not create a result set" {
		fmt.Println(err)
		fmt.Println("error while creating sp1")
	}
	st, err = db.Prepare("CALL sp1(?,?,?)")
	if err != nil {
		fmt.Println("error while preparing sp1 CALL")
	}
	_, err = st.Query(in1, sql.Out{Dest: &out1}, sql.Out{Dest: &inout1, In: true})
	if err.Error() != "Stmt did not create a result set" {
		fmt.Println(err)
		fmt.Println("error while retriving data for sp1 with prepare")
	}

	if inout1 != "SUCCESS" || out1 != "1234567" {
		fmt.Println("Data not Retrived Correctly in prepare")
		fmt.Println(out1)
		fmt.Println(inout1)
	} else {
		fmt.Println(out1)
		fmt.Println(inout1)
	}
	inout1 = "1234567"
	_, err = db.Exec("CALL sp1(?,?,?)", in1, sql.Out{Dest: &out1}, sql.Out{Dest: &inout1, In: true})
	if err != nil {
		fmt.Println("error while retriving data for sp1 with execute")
	}

	if inout1 != "SUCCESS" || out1 != "1234567" {
		fmt.Println("Data not Retrived Correctly in execute")
		fmt.Println(out1)
		fmt.Println(inout1)
	} else {
		fmt.Println(out1)
		fmt.Println(inout1)
	}
}

```

**Comment by akhilravuri1** [comment] 2020-07-24 16:06
Hi @Speshl 

Now I am able to reproduce the issue.
I am working on it.

I will try to merge the pull req by today.

Thanks,
Akhil

**Comment by akhilravuri1** [comment] 2020-07-24 16:25
Sorry for the delay.

Merged the pull request.

Thanks,
Akhil

**Closed** 2020-08-18 15:22 UTC
